Support faraday 2.0 & streaming api
lostisland/faraday-http pull request #32
Opened 2022-10-21 07:35 UTC by aka-nez

Hi! I tried to update the gem to make it compatible with Faraday 2 and add streaming API support.

Take a look. please @iMacTia

2022-10-21 07:52 UTC, iMacTia reviewed
Thank you @aka-nez 🙌!

Agree about the CI matrix, please make it cover 2.6 -> 3.1 like we do in Faraday.

Out of curiosity, could you explain why you needed to explicitly add the `faraday/multipart` middleware? What kind of errors were you seeing otherwise?

2022-10-21 07:59 UTC, aka-nez commented
> Out of curiosity, could you explain why you needed to explicitly add the `faraday/multipart` middleware? What kind of errors were you seeing otherwise?

spec/faraday/http/adapter_spec.rb:26 uses this middleware, that was bundled with Faraday before

2022-10-21 08:05 UTC, iMacTia commented
Thanks for clarifying!
I saw you added it to the Gemfile and `spec_helper`, so there should be no impact on users of this gem 👍

2022-10-21 08:17 UTC, aka-nez commented
I have updated the CI matrix and entirely removed everything related to multipart. It doesn't impact tests

2022-10-21 13:22 UTC, olleolleolle commented
(I did some cleaning out of earlier Required Build Checks, which included now-removed ones.)

2022-10-21 13:25 UTC, olleolleolle commented
Ah, I noted this in the failure in CI:

>   Gems in the groups 'development' and 'test' were not installed.

Perhaps some --deployment flag is enabled>

2022-10-21 13:50 UTC, aka-nez commented
Removed this line from ci

2022-10-21 13:55 UTC, olleolleolle commented on faraday-http.gemspec
> +  spec.metadata['rubygems_mfa_required'] = 'true'
Suggestion: Can we move this line to sit just after "changelog_uri"?

2022-10-21 13:59 UTC, aka-nez commented on faraday-http.gemspec
> +  spec.metadata['rubygems_mfa_required'] = 'true'
Sure. My bad, it was rubocop -a correction. Fixed.

2022-10-21 14:35 UTC, olleolleolle commented
@iMacTia Are we ready to go, here?

2022-10-21 16:44 UTC, iMacTia requested changes
Actually, `faraday ~> 2.0` is incorrect, we should pin to `faraday ~> 2.5` as older versions don't have the [new streaming API](https://github.com/lostisland/faraday/releases/tag/v2.5.0). Tests are passing because bundler installs the latest version, which works fine.

2022-10-21 17:32 UTC, aka-nez commented
> Actually, `faraday ~> 2.0` is incorrect, we should pin to `faraday ~> 2.5` as older versions don't have the [new streaming API](https://github.com/lostisland/faraday/releases/tag/v2.5.0). Tests are passing because bundler installs the latest version, which works fine.

Sure. Fixed! 👍

2022-10-22 14:06 UTC, iMacTia approved these changes

2022-10-22 14:06 UTC, merged

2022-10-22 14:07 UTC, iMacTia commented
Thank you so much @aka-nez, I'm gonna drop a release soon 🙌 !